### ISSUE TITLE
训练时长问题

### ISSUE THREAD

**Issue by Cannizza-zzk** [williamliujl/Qilin-Med#3]
您好，注意到您的论文中提到cpt，sft两阶段实验是在A100服务器上完成，想请问您具体使用了多少运算资源，两个阶段的微调耗时多少？同时注意到您的实验设置中 max_source_length、max_target_length均为256，这个长度是否会影响到模型的最终性能，有没有做相关实验？

**Comment by williamliujl** [comment]
均使用8 x A100 80G
1. 一阶段耗时两天
2. 二阶段耗时一天
max_length参数优化我们暂时还没有做相关实验，欢迎一起讨论探索。
